apiVersion: apps/v1
kind: Deployment
metadata:
  name: kk-payments
  labels:
    app: kk-payments

spec:
  replicas: 3
  revisionHistoryLimit: 10

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  selector:
    matchLabels:
      app: kk-payments

  template:
    metadata:
      labels:
        app: kk-payments

    spec:
      imagePullSecrets:
        - name: kijani-registry-credentials

      containers:
        - name: kk-payments
          image: lewis0648/kk-payments:PIPELINE_REQUIRED
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 3001

          envFrom:
            - configMapRef:
                name: kk-payments-config

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
